Feature/functionality security doc
elirosselli/pis2020 pull request #116
Opened 2020-11-26 21:16 UTC by manueleirea

# Security documentation

## Descripción

Se documentó el componente de seguridad, actualizando la documentación de las otras funcionalidades según correspondiera. Se actualizaron los errores retornados por cada funcionalidad, tanto en el *CONTRIBUTING* como en el *README*.

## Tests

No aplica.

2020-11-26 21:42 UTC, sebalagomarsino commented on sdk/CONTRIBUTING.md
> +El código de la función consiste en generar una semilla aleatoria con la librería *Math*, luego con la librería MersenneTwister obtener un generador aleatorio con dicha semilla, y finalmente con ese
```suggestion
El código de la función consiste en generar una semilla aleatoria con la librería *Math*, luego con la librería *MersenneTwister* obtener un generador aleatorio con dicha semilla, y finalmente con ese generador obtener un número entero aleatorio. El valor es retornado en forma de *string*.
```

2020-11-26 21:42 UTC, sebalagomarsino commented on sdk/CONTRIBUTING.md
> +En primer lugar, esta función obteniene la clave pública del endpoint a partir de los atributos *n* y *m* del la *jwksResponse*. Tomando esta clave pública, la compara con la clave pública incluida e
```suggestion
En primer lugar, esta función obteniene la clave pública del endpoint a partir de los atributos *n* y *m* del la *jwksResponse*. Tomando esta clave pública, la compara con la clave pública incluida en el *idToken*, además de validar otros parámetros como son el algoritmo de encriptación utilizado, el *issuer*, el auditor al cual va dirigido el *idToken* (*clientId*) y comprueba que no esté expirado.
```

2020-11-26 21:42 UTC, sebalagomarsino commented on sdk/CONTRIBUTING.md
> +El funcionamiento general de **initialize** consiste en establecer los parámetros mencionados. En primer lugar, se chequea que los parámetros no sean vacíos (excepto por *scope*). Si alguno o varios
```suggestion
El funcionamiento general de **initialize** consiste en establecer los parámetros mencionados. En primer lugar, se chequea que los parámetros no sean vacíos (excepto por *scope*). Si alguno o varios de estos son vacíos entonces se lanza una excepción, retornando el error correspondiente según el primer parámetro vacío encontrado. En cambio, si los parámetros necesarios son válidos, se *setean* en el componente de configuración utilizando la función **setParameters** y se retorna un mensaje indicando que no hubo error. Una vez que se *setean* estos parámetros (excepto por el *scope*) no es posible *setear* su valor a vacío nuevamente.
```

2020-11-26 21:42 UTC, sebalagomarsino commented on sdk/CONTRIBUTING.md
> +- **sdk/security/index.js**: Donde se implementa la función **generateRandomState**, encargada de generar un parámetro *state* random.
```suggestion
- **sdk/security/index.js**: Donde se implementa la función **generateRandomState**, encargada de generar un *state* aleatorio.
```
Me parece que estaba bien como estaba antes.

2020-11-26 21:42 UTC, sebalagomarsino commented on sdk/CONTRIBUTING.md
> -- Cuando el parámetro *production* no es booleano: `ERRORS.INVALID_PRODUCTION`
Te lo pongo en este pero va para todos los lados que lo sacaste, porque sacaste el INVALID_PRODUCTION?

2020-11-26 21:45 UTC, elirosselli requested changes
no me odies :see_no_evil:

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- ***validateTokenSecurity***: Encargada de validar el *token*, a través de un *jwk* recibido en una *response* del OP.
acá el "recibido por el OP" es el token? creo que queda medio confuso si es el token o el jwk

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- **sdk/security/validateParameters/BOOLEAN.js**: Donde se implementa una función utilizada por **validateParameters**.
```suggestion
- **sdk/security/validateParameters/BOOLEAN.js**: Donde se implementa una función utilizada por **validateParameters** para validar parámetros booleanos.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- **sdk/security/validateParameters/DIGIT.js**: Donde se implementa una función utilizada por **validateParameters**.
```suggestion
- **sdk/security/validateParameters/DIGIT.js**: Donde se implementa una función utilizada por **validateParameters** para validar parámetros númericos.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- **sdk/security/validateParameters/NQCHAR.js**: Donde se implementa una función utilizada por **validateParameters**.
```suggestion
- **sdk/security/validateParameters/NQCHAR.js**: Donde se implementa una función utilizada por **validateParameters** para validar parámetros de tipo NQCHAR.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- **sdk/security/validateParameters/URIReference.js**: Donde se implementa una función utilizada por **validateParameters**.
```suggestion
- **sdk/security/validateParameters/URIReference.js**: Donde se implementa una función utilizada por **validateParameters** para validar parámetros de tipo URI.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- **sdk/security/validateParameters/VSCHAR.js**: Donde se implementa una función utilizada por **validateParameters**.
```suggestion
- **sdk/security/validateParameters/VSCHAR.js**: Donde se implementa una función utilizada por **validateParameters** para validar parámetros de tipo VSCHAR.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +El código de la función consiste en generar una semilla aleatoria con la librería *Math*, luego con la librería MersenneTwister obtener un generador aleatorio con dicha semilla, y finalmente con ese
Agregaría, antes de la parte de 'El valor es retornado', una frase diciendo que la librería usa el algoritmo Mersenne Twister (medio obvio pero ta), tipo:
```markdown
Dicha librería utiliza el algortimo [Mersenne Twister](https://en.wikipedia.org/wiki/Mersenne_Twister) para la generación de números pseudoaleatorios.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +| clientId      | Id de cliente asignado por idUruguay.                                                 |
diría clientId asignado por idUruguay porque creo que siempre le decimos así,  y no 'id de cliente', pero no se que te parece

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +En primer lugar, esta función obteniene la clave pública del endpoint a partir de los atributos *n* y *m* del la *jwksResponse*. Tomando esta clave pública, la compara con la clave pública incluida e
issuer en cursiva :)

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +Posteriormente decodifica el *header* y el *payload*. Del *header* valida el *kid* que es un identificador único incluido tanto en el *idToken* como en el *jwksResponse*. Además, valida que el ACR (A
```suggestion
Posteriormente decodifica el *header* y el *payload*. Del *header* valida el *kid* que es un identificador único incluido tanto en el *idToken* como en el *jwksResponse*. Además, valida que el ACR (*Authentication Context Class Reference*) y el AMR (*Authentication Methods References*) asignados estén entre los definidos en el archivo de constantes.
```

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +Si se cumplen todas las condiciones mencionadas se resuelve la promesa con la *jwksResponse* y un error de tipo *ERRORS.NO_ERROR*. En caso contrario se rechaza la promesa con un error de tipo *ERRORS
en vez de error de tipo ERRORS.NO_ERROR podemos decir directo ' y se devuelve ERRORS.NO_ERROR' ?

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +En primer lugar, se chequea que los parámetros que no pueden ser vacíos (*clientId*, *clientSecret*, *redirectUri* y *production*) no lo sean. En caso de que no sean vacíos, se chequea si *scope* fue
el mensaje message al final sigue estando?

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- **sdk/security/index.js**: Donde se implementa la función **generateRandomState**, encargada de generar un parámetro *state* random.
dejaría 'aleatorio' en vez de random, salvo que por alguna razón esté incorrecto?

2020-11-26 21:45 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +- Cuando el parámetro *code* sea inválido o haya expirado, y no se pueda obtener un nuevo *token* de forma satisfactoria: `ERRORS.INVALID_GRANT`
para dejar consistente el tiempo verbal (todos los otros dicen 'es'), diría:

Cuando el parámetro *code* es inválido o está expirado, y no se puede obtener un nuevo *token* de forma satisfactoria: `ERRORS.INVALID_GRANT`

2020-11-26 21:46 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> -- Cuando el parámetro *production* no es booleano: `ERRORS.INVALID_PRODUCTION`
creo que porque ya no se devuelve, por defecto es false y nunca lo van a poder settear a algo inválido no?

2020-11-26 21:56 UTC, manueleirea commented on sdk/CONTRIBUTING.md
> -- Cuando el parámetro *production* no es booleano: `ERRORS.INVALID_PRODUCTION`
Ahí va, es por eso. Si no se inicializa queda en false, y si lo fueran a setear a algo no booleano te tiraría error ahí

2020-11-26 21:58 UTC, sebalagomarsino commented on sdk/CONTRIBUTING.md
> -- Cuando el parámetro *production* no es booleano: `ERRORS.INVALID_PRODUCTION`
Entiendo, perfecto.

2020-11-26 22:02 UTC, manueleirea commented on sdk/CONTRIBUTING.md
> +En primer lugar, se chequea que los parámetros que no pueden ser vacíos (*clientId*, *clientSecret*, *redirectUri* y *production*) no lo sean. En caso de que no sean vacíos, se chequea si *scope* fue
Sí, el error del login es: ``

2020-11-26 22:43 UTC, elirosselli approved these changes

2020-11-27 15:45 UTC, sebalagomarsino approved these changes

2020-11-27 15:47 UTC, merged