Feature/get token with tests
elirosselli/pis2020 pull request #23
Opened 2020-10-14 01:35 UTC by facugu1998

# Funcionalidad GetToken

## Descripción

Se implementa la funcionalidad GetToken, que se encarga de la comunicación con el TokenEndpoint, y la obtención de los datos pertinentes.
La implementación actual requiere del uso de la librería 'react-native-ssl-pinning' que resuelve el problema del certificado autofirmado. Actualmente funciona únicamente en Android.

## Tests

Pruebas unitarias
  - [x] Llamar a getToken con la información correcta, esperando la devolución del access token correspondiente.
  - [x] Llamar a getToken con un código incorrecto, esperando una respuesta con status 400 y el contenido correspondiente.
  - [x] Llamar a getToken con clientId o clientSecret incorrecto, esperando una respuesta con status 400 y el contenido correspondiente.

2020-10-14 13:16 UTC, sebalagomarsino requested changes
Faltaria: 
- Agregar los parámetros nuevos al componente de configuración (accessToken, refreshToken, tokenType, expiresIn, idToken). Al hacer este cambio se tienen que actualizar los tests de esta componente.
- Actualizar los tests de login para que no fallen, por el cambio en la función makeRequest que ahora es async.

2020-10-14 13:16 UTC, slagomarsino-fing commented on app/LoginButton/index.js
> +      console.log(token);
```suggestion
      console.log(`Token: ${token}`);
```

2020-10-14 13:16 UTC, slagomarsino-fing commented on app/package.json
> +    "fetch-blob": "^2.1.1",
Esta libreria no se utiliza

2020-10-14 13:16 UTC, slagomarsino-fing commented on app/package.json
> +    "rn-fetch-blob": "^0.12.0"
Esta libreria no se utiliza

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/interfaces/index.js
> +    return response;
```suggestion
    return await makeRequest(REQUEST_TYPES.GET_TOKEN);
```

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    expect.assertions(2);
Considero que no es necesario esto, dado que el test tiene que acertar en los próximos dos expects, si falla el expect, falla el test.

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    const response = makeRequest(REQUEST_TYPES.GET_TOKEN);
```suggestion
    const response = await makeRequest(REQUEST_TYPES.GET_TOKEN);
```

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    expect.assertions(1);
Considero que no es necesario esto, dado que el test tiene que acertar en los próximos dos expects, si falla el expect, falla el test.

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    );
```suggestion
    const response = await makeRequest(REQUEST_TYPES.GET_TOKEN);
```

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    });
Considero que lo podrías poner sin el return, como hiciste con los otros tests para que el código sea todo "igual".

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    expect.assertions(1);
Considero que no es necesario esto, dado que el test tiene que acertar en los próximos dos expects, si falla el expect, falla el test.

2020-10-14 13:16 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +              'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)',
Podrías poner el valor de error, y de error_description en una constante, para reutilizarla en el expect.

2020-10-14 21:27 UTC, facugu1998 commented on sdk/requests/__tests__/index.test.js
> +              'Client authentication failed (e.g., unknown client, no client authentication included, or unsupported authentication method)',
Quedó definido con variables.

2020-10-14 21:30 UTC, facugu1998 commented on sdk/requests/__tests__/index.test.js
> +    expect.assertions(1);
Quedaron sin assertion.

2020-10-14 21:32 UTC, facugu1998 commented on sdk/requests/__tests__/index.test.js
> +    });
Quedó solucionado.

2020-10-15 14:08 UTC, sebalagomarsino approved these changes

2020-10-15 15:10 UTC, ssantiacevedo approved these changes

2020-10-15 15:17 UTC, merged