Feature/make request refresh token
elirosselli/pis2020 pull request #24
Opened 2020-10-15 04:35 UTC by belenbrandino

## Descripción

Se implementó la funcionalidad de Make Request Refresh Token, que a partir de un refresh_token obtiene un nuevo access_token.
La implementación actual requiere del uso de la librería 'react-native-ssl-pinning' que resuelve el problema del certificado autofirmado. Actualmente funciona únicamente en Android. También se implementó parcialmente la funcionalidad de refreshToken.

## Tests

Explique las pruebas unitarias realizadas. Por ejemplo, con una lista:
- [ ] Llamar a makeRequest con REQUEST_TYPES.GET_REFRESH_TOKEN y la información correspondiente, esperando la devolución del access token nuevo.
- [ ]   Llamar a makeRequest con REQUEST_TYPES.GET_REFRESH_TOKEN con parametros incorrectos, esperando una respuesta con status 400 y el contenido correspondiente.
- [ ]   Llamar a makeRequest con REQUEST_TYPES.GET_REFRESH_TOKEN cuando falla el fetch, esperando un mensaje de error.

- [ ]   Llamar a refreshToken, esperando un nuevo access_token.
- [ ]   Llamar a refreshToken, esperando un mensaje de error.

2020-10-15 13:08 UTC, ssantiacevedo commented on sdk/requests/index.js
> +      // eslint-disable-next-line eqeqeq
Por qué fue necesario desactivsar el linter? Y ese eqeqeq quedo por error?

2020-10-15 15:43 UTC, belenbrandino commented on sdk/requests/index.js
> +      // eslint-disable-next-line eqeqeq
dice que espera tres iguales en vez de dos

2020-10-15 15:45 UTC, ssantiacevedo commented on sdk/requests/index.js
> +      // eslint-disable-next-line eqeqeq
Esta bien eso, el linter de JS te hace === para comparación booleana.

2020-10-15 19:14 UTC, ssantiacevedo approved these changes

2020-10-15 20:52 UTC, sebalagomarsino commented on sdk/index.js
> +/* eslint-disable import/prefer-default-export */
Este disable no es necesario.

2020-10-15 20:52 UTC, sebalagomarsino commented on app/LoginButton/index.js
> +// eslint-disable-next-line import/no-unresolved
Este disable no es necesario. Ya esta `/* eslint-disable import/no-extraneous-dependencies */` en la primer linea del archivo.

2020-10-15 20:52 UTC, sebalagomarsino commented on sdk/interfaces/index.js
> +};
```suggestion
const refreshToken = () => makeRequest(REQUEST_TYPES.GET_REFRESH_TOKEN);
```

2020-10-15 20:52 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    expect.assertions(2);
Este assert no es necesario. El código tiene que acertar en los próximos dos expects.

2020-10-15 20:52 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +  it('calls getToken with incorrect clientId or clientSecret or refreshToken', async () => {
```suggestion
  it('calls refreshToken with incorrect clientId or clientSecret or refreshToken', async () => {
```

2020-10-15 20:57 UTC, sebalagomarsino commented on sdk/requests/index.js
> +    case REQUEST_TYPES.GET_REFRESH_TOKEN: {
```suggestion
    case REQUEST_TYPES.GET_TOKEN || REQUEST_TYPES.GET_REFRESH_TOKEN: {
```
Creo que lo podes poner así, me parece que queda mas lindo, pero no estoy seguro si funciona

2020-10-15 21:46 UTC, sebalagomarsino commented on app/LoginButton/index.js
>        const token = await getToken(code);
```suggestion
      const token = await getToken();
```
Ya se que no es de tu pr, pero si podes cambiarlo :)

2020-10-16 12:16 UTC, sebalagomarsino requested changes

2020-10-16 12:16 UTC, sebalagomarsino commented on sdk/requests/index.js
> +      return getToken(type);
```suggestion
      return getOrRefreshToken(type);
```
Debería tener un nombre más específico para no confundir a los desarrolladores.

2020-10-16 12:16 UTC, sebalagomarsino commented on sdk/requests/constants.js
> +export default REQUEST_TYPES;
Esto está muy bueno. Pero al agregar esto hay que actualizar todos los tests para que se importen correctamente los `REQUEST_TYPES`.

2020-10-16 12:16 UTC, sebalagomarsino commented on sdk/requests/getToken.js
> +const getToken = async type => {
El archivo y la función se deberían de llamar getOrRefreshToken para ser más específicos y no confundir a los programadores. Al mover la función a un archivo separado es necesario actualizar los tests.

2020-10-17 15:27 UTC, sebalagomarsino commented on sdk/requests/__tests__/refreshToken.test.js
> +    expect.assertions(2);
`expect.assertions(2)` no es necesario en este caso, dado que el código tiene que cumplir los próximos dos expects sino fallará.

2020-10-17 15:27 UTC, sebalagomarsino commented on sdk/requests/__tests__/refreshToken.test.js
> +  it('calls refreshToken and fetch fails', async () => {
Si podes ponele un espacio acá así quedan separados los `it`.
```suggestion
  });
  
  it('calls refreshToken and fetch fails', async () => {
```

2020-10-17 15:43 UTC, ssantiacevedo approved these changes

2020-10-17 15:43 UTC, sebalagomarsino approved these changes

2020-10-17 15:44 UTC, merged