Feature/logout
elirosselli/pis2020 pull request #26
Opened 2020-10-16 18:09 UTC by manueleirea

## Descripción

Se implementó la funcionalidad de logout. Esta toma los parámetros idToken, postLogoutRedirectUri, y opcionalmente state, y envía una solicitud al Logout Endpoint de la API con estos parámetros, cerrando la sesión del usuario final en el OP. Se abre además un browser mediante la librería Linking de react-native, que muestra al usuario final que efectivamente se está realizando el logout. Actualmente, desde la app prototipo se puede invocar esta funcionalidad mediante el LoginButton, una vez ya realizada una autenticación.

## Tests

Se implementaron las siguientes pruebas unitarias:
  - [x] Llamar a logout con REQUEST_TYPES.LOGOUT, los parámetros necesarios (idToken y postLogoutredirectUri) y state, esperando la devolución de la postLogoutRedirectUri.
  - [x] Llamar a logout con REQUEST_TYPES.LOGOUT y los parámetros necesarios (sin state), esperando la devolución de la postLogoutRedirectUri.
  - [x] Llamar a logout con REQUEST_TYPES.LOGOUT, idToken y state (sin postLogoutRedirectUri) esperando un mensaje de error.
  - [x] Llamar a logout con REQUEST_TYPES.LOGOUT, postLogoutRedirectUri y state (sin idToken) esperando un mensaje de error.
  - [x] Llamar a logout esperando un mensaje de error.
  - [x] Llamar a logout esperando la devolución de la postLogoutRedirectUri.

2020-10-16 21:55 UTC, elirosselli requested changes
Hola :) Dejé algunos comentarios

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/__tests__/logout.test.js
> +      state: 'chau',
Capaz que en vez de 'chau' le podemos poner 'testState', solo para que quede más "formal" :joy:

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/__tests__/logout.test.js
> +      'https://auth-testing.iduruguay.gub.uy/oidc/v1/logout?id_token_hint=idToken&post_logout_redirect_uri=postLogoutRedirectUri2&state=',
Capaz que se podría obtener el endpoint del archivo de endpoints, así no queda hardcodeado en el test :)

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/__tests__/logout.test.js
> +      state: 'chau',
Lo mismo que en el otro, cambiar el state a 'testState'o similar

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/__tests__/logout.test.js
> +      state: 'chau',
idem :see_no_evil:

2020-10-16 21:55 UTC, elirosselli commented on app/LoginButton/index.js
> +    else await handleLogout();
Esto es lo que hablamos que es medio raro no? Igual yo ahora lo dejaría así, porque es parte de la tarea U3 + TU3 dejar prolijo el tema del logout en la app

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/logout.js
> +const logout = async () => {
La función está re bien, le agregaría algunos comentarios para que se entienda más y sea más fácil de documentar (se pueden usar y adaptar los del login porque son funciones muy parecidas)

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/logout.js
> +    } else rejectFunction(Error('Invalid post logout redirect uri'));
Esta línea no la estamos testeando, de momento no me estoy dando cuenta si podemos testearla pero si no podemos es problemático para el coverage. También tengo la duda de si es posible que urlCheck venga vacía :thinking:

2020-10-16 21:55 UTC, elirosselli commented on sdk/requests/logout.js
> +  }
Estas líneas también quedaron sin testear, creo que se pueden testear haciendo que el mock de Linking.openUrl tire un error

2020-10-16 22:24 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +      state: 'chau',
Me parece bien! Yo le puse "chau" porque es lo que decía literalmente en el documento de pruebas unitarias

2020-10-16 22:29 UTC, sebalagomarsino commented on sdk/requests/logout.js
> +      rejectFunction(Error("Couldn't make request"));
```suggestion
      rejectFunction(Error("Didn't provide idToken nor postLogoutRedirectUri"));
```
Me parece que queda mucho más explícito el error. Yo le voy a cambiar eso para que el login lo tenga.

2020-10-16 22:33 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +      'https://auth-testing.iduruguay.gub.uy/oidc/v1/logout?id_token_hint=idToken&post_logout_redirect_uri=postLogoutRedirectUri2&state=',
El tema es que si lo saco de ahí ya me viene con el idToken y post...Uri, porque en endpoints ya se hace el getParams y te lo devuelve con eso

2020-10-16 22:37 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +      'https://auth-testing.iduruguay.gub.uy/oidc/v1/logout?id_token_hint=idToken&post_logout_redirect_uri=postLogoutRedirectUri2&state=',
Si, coincido con Manu, para mi si no lo hardcodeas pierde el sentido la prueba, porque pondrías toHaveBeenCalledWith(logoutEndpoint()), sin saber lo que hay ahí adentro.

2020-10-16 22:47 UTC, sebalagomarsino requested changes

2020-10-16 22:47 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +    expect.assertions(1);
Este test no esta haciendo lo que vos queres que haga. Te falta agregarle `mockAddEventListener.mockImplementation()` para sacar lo que implementaste en los tests anteriores de la respuesta del eventListener. Cuando agregues eso, te va a fallar en este assert y tener que cambiarlo por `expert.assertions(2)`

2020-10-16 22:47 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +    expect.assertions(1);
Lo mismo que el comentario anterior.

Este test no esta haciendo lo que vos queres que haga. Te falta agregarle `mockAddEventListener.mockImplementation()` para sacar lo que implementaste en los tests anteriores de la respuesta del eventListener. Cuando agregues eso, te va a fallar en este assert y tener que cambiarlo por `expert.assertions(2)`

2020-10-16 22:47 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +  it('calls logout with idTokenHint, postLogoutRedirectUri and state', async () => {
Por qué pusiste idTokenHint en vez de idToken?

2020-10-17 12:06 UTC, elirosselli commented on sdk/requests/__tests__/logout.test.js
> +      state: 'chau',
uh, me sigue pareciendo bien cambiarlo pero les avisaría a los de verificación por las dudas

2020-10-17 12:07 UTC, elirosselli commented on sdk/requests/__tests__/logout.test.js
> +      'https://auth-testing.iduruguay.gub.uy/oidc/v1/logout?id_token_hint=idToken&post_logout_redirect_uri=postLogoutRedirectUri2&state=',
ahh, entiendo. Ignoren mi comentario en ese caso.

2020-10-17 12:09 UTC, elirosselli commented on sdk/requests/logout.js
> +      rejectFunction(Error("Couldn't make request"));
Creo que el 'nor' debería ser un 'or' :) Sino algo tipo Mising required parameter: idToken / missingRequiredParameter: postLogoutRedirectUri (no sé si podemos distinguir cual falta, si no ponerlos ambos)

2020-10-17 15:45 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +      state: 'chau',
Coincido con Eli!

2020-10-18 15:08 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +  it('calls logout with idTokenHint, postLogoutRedirectUri and state', async () => {
Porque el parámetro en la request de logout se llama así

2020-10-18 17:37 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +  it('calls logout with idTokenHint, postLogoutRedirectUri and state', async () => {
Si se llama así, no deberíamos de guardarlo en los parámetros con ese nombre entonces? Para no confundirnos y que parezcan que son dos cosas distintas

2020-10-18 22:08 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +  it('calls logout with idTokenHint, postLogoutRedirectUri and state', async () => {
El tema es que el getToken te lo devuelve como idToken pero después el logout te lo pide como idTokenHint :)

2020-10-18 22:09 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +  it('calls logout with idTokenHint, postLogoutRedirectUri and state', async () => {
O sea, el logout tiene un parámetro que es id_token_hint, y en la descripción dice "Corresponde al `id_token` obtenido en el mecanismo de inicio de sesión (...)"

2020-10-18 23:39 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +  it('calls logout with idTokenHint, postLogoutRedirectUri and state', async () => {
Ahhh, ahi va, excelente Manu, ahí me quedó claro!

2020-10-19 22:41 UTC, sebalagomarsino requested changes
Siguen faltando testear las líneas 30, 56 y 57 del archivo `logout.js` de la carpeta `requests`. Mañana si queres te ayudo!

2020-10-19 22:41 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/logout.test.js
> +  it('calls logout and fails', async () => {
```suggestion
  });
  
  it('calls logout and fails', async () => {
```
Para que queden separado cada it.

2020-10-19 22:41 UTC, sebalagomarsino commented on sdk/interfaces/index.js
> +const logout = async () => makeRequest(REQUEST_TYPES.LOGOUT);
```suggestion
const logout = () => makeRequest(REQUEST_TYPES.LOGOUT);
```

2020-10-19 22:41 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
>  }));
```suggestion
afterEach(() => jest.clearAllMocks());
```

2020-10-19 22:41 UTC, sebalagomarsino commented on sdk/utils/endpoints.js
> +  );
```suggestion
  return `https://auth-testing.iduruguay.gub.uy/oidc/v1/logout?id_token_hint=${idToken}&post_logout_redirect_uri=${postLogoutRedirectUri}&state=${state}`;
```
Este chequeo es redundante dado que ya lo haces en la línea 40 del archivo `logout.js` en la carpeta `requests`.

2020-10-20 21:17 UTC, sebalagomarsino requested changes

2020-10-20 21:17 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +    });
El plugin de Sonarqube de eslint falla en la línea 46. Falla porque dice que se repite exactamente el mismo código que en la línea 28.

2020-10-20 21:17 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +const missingParams = 'Missing required parameter(s): ';
```suggestion
const missingParamsMessage = 'Missing required parameter(s): ';
```
Para no confundirnos con el objeto que tiene los parámetros. Si se acepta la sugerencia, es necesario cambiar la constante en todo el archivo.

2020-10-20 21:17 UTC, sebalagomarsino commented on sdk/requests/logout.js
> +  const missingParams = 'Missing required parameter(s): ';
```suggestion
  const missingParamsMessage = 'Missing required parameter(s): ';
```
Para no confundirnos con el objeto que tiene los parámetros. Si se acepta la sugerencia, es necesario cambiar la constante en todo el archivo.

2020-10-20 23:55 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +    });
True, me lo comí ese. Si saco eso para afuera del describe y no lo pongo en cada test ta bien?

2020-10-20 23:58 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +    });
No, si lo sacas para afuera el test no va a hacer lo queres porque no se estaría mockeando la implementación cada vez, hay que tener cuidado con eso. Si lo sacas para afuera va a quedar con la implementación anterior, que justo en este caso es la misma. Me parece que lo mejor es que le pongas un valor distinto a la url para que el linter no te diga que es lo mismo

2020-10-20 23:59 UTC, elirosselli approved these changes

2020-10-20 23:59 UTC, manueleirea commented on sdk/requests/__tests__/logout.test.js
> +    });
Ahh bien, hago eso entonces

2020-10-21 00:16 UTC, sebalagomarsino approved these changes

2020-10-21 00:18 UTC, merged