Feature/respaldo after login display
elirosselli/pis2020 pull request #40
Opened 2020-10-23 20:34 UTC by facugu1998

# After Login Display

## Descripción

Se modifica la interfaz de usuario agregando las siguientes funciones:

- Seleccionar el scope antes de hacer login.
- Inicializar el sdk con un botón y no automáticamente.
- Obtener el token con un botón dedicado.
- Refresh del token con un botón.
- Obtener la user info con un botón.
- Logout con un botón.

## Tests

No corresponde.

2020-10-24 20:45 UTC, sebalagomarsino requested changes

2020-10-24 20:45 UTC, sebalagomarsino commented on app/package.json
> +    "@react-native-community/checkbox": "^0.5.5",
```suggestion
```
No se utiliza esta librería.

2020-10-24 20:45 UTC, sebalagomarsino commented on app/package.json
> +    "react-native-ssl-pinning": "^1.5.1",
```suggestion

```
No se utilizan estas librería.

2020-10-24 20:46 UTC, sebalagomarsino requested changes

2020-10-24 20:46 UTC, sebalagomarsino commented on sdk/interfaces/index.js
> +  });
scope no deberia de ser inicializado en la función initialize, debería ser setteado a través de la función setParameters.

2020-10-25 14:17 UTC, facugu1998 commented on app/package.json
> +    "@react-native-community/checkbox": "^0.5.5",
Resuelto.

2020-10-25 14:18 UTC, facugu1998 commented on app/package.json
> +    "react-native-ssl-pinning": "^1.5.1",
Listo.

2020-10-25 17:37 UTC, ssantiacevedo commented on sdk/interfaces/index.js
> +  });
Coincido

2020-10-26 19:02 UTC, facugu1998 commented on app/package.json
> +    "react-native-ssl-pinning": "^1.5.1",
Si borro el react-native-ssl-pinning deja de andar bien

2020-10-26 19:19 UTC, facugu1998 commented on sdk/interfaces/index.js
> +  });
Cambiado

2020-10-26 22:19 UTC, sebalagomarsino approved these changes
Se aprueba el PR para mercera y que pueda ser revisado por SQA. El código deberá ser refactoreado y la interfaz de usuario en iOS deberá mejorar.

2020-10-26 22:19 UTC, merged