Feature/request validate token
elirosselli/pis2020 pull request #49
Opened 2020-11-03 04:58 UTC by facugu1998

# Validate Token

## Descripción

Se implementa validate token, la función en request y la función en el componente de seguridad, junto a sus respectivos tests unitarios.

## Tests

 Pruebas de request validate token:
  - [x] calls validateToken correctly and token is valid: se invoca correctamente a la función validateToken y el token es válido 
  - [x] calls validateToken correctly but token is not valid: se invoca correctamente a la función validateToken pero el token es inválido.

Pruebas de validate token en componente seguridad:

 - [x] validates token correctly: el token es válido
 - [x] not validates token (payload): el token es inválido, falla la función KJUR.jws.JWS.verifyJWT
 - [x] not validates token (kid): el token es inválido, kid no coincide

2020-11-04 22:20 UTC, sebalagomarsino requested changes

2020-11-04 22:20 UTC, sebalagomarsino commented on sdk/requests/__tests__/validateToken.test.js
> +    expect.assertions(1);
Este código no está haciendo lo deseado. Por qué este expect es assertions = 1 ? el coding no esta entrando a alguno de los dos expect

2020-11-04 22:20 UTC, sebalagomarsino commented on sdk/utils/encoding.js
> +  // Pad out with standard base64 required padding characters
Cambiar comentarios a español.

2020-11-04 22:20 UTC, sebalagomarsino commented on sdk/security/index.js
> +  // Se valida el kid del token
Estaria bueno explicar en algún lugar que son los campos kid, alg, iss aud, a simple vista no se entiende que significan. Ponerle `.` al final de todos los comentarios por favor

2020-11-04 22:20 UTC, sebalagomarsino commented on sdk/requests/__tests__/validateToken.test.js
> +      Promise.resolve(new Error({ jwks: jwksResponse, error: false })),
No es necesario la palabra `new`

2020-11-05 17:40 UTC, facugu1998 commented on sdk/utils/encoding.js
> +  // Pad out with standard base64 required padding characters
Listo.

2020-11-05 17:40 UTC, facugu1998 commented on sdk/requests/__tests__/validateToken.test.js
> +    expect.assertions(1);
Ahí creo que quedó, lo había dejado como antes y no lo había corregido.

2020-11-05 17:40 UTC, facugu1998 commented on sdk/security/index.js
> +  // Se valida el kid del token
Quedaron los comentarios y las descripciones de los campos.

2020-11-08 16:55 UTC, sebalagomarsino requested changes

2020-11-08 16:55 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/validateToken.test.js
> +  it('calls validateToken with invalid token', async () => {
Falta tests cuando el makeRequest devuelve `Promise.reject(`

2020-11-08 16:55 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    validateToken.mockReturnValue(Promise.resolve(result));
Falta test cuando validateToken devuelve `Promise.reject(`

2020-11-08 16:55 UTC, sebalagomarsino commented on sdk/requests/__tests__/validateToken.test.js
> +  });
Este test no lo entiendo. Se hace expect de validateTokenSecurity antes de que se llame a validateToken, debería ser después y validateToken creo que debería de estar en un try-catch

2020-11-08 16:55 UTC, sebalagomarsino commented on sdk/requests/validateToken.js
> +};
Falta ponerle comentarios a esta función. También falta el workaround que se utilizo en las otras funciones de crear una premies y ver que hacer en base al resultado que se obtiene del fetch.

2020-11-08 16:55 UTC, sebalagomarsino commented on sdk/security/validateTokenSecurity.js
> +  // Se valida el kid del token.
Qué es el kid? Agregar una breve descripción en el código por favor.

2020-11-08 16:55 UTC, sebalagomarsino commented on sdk/security/validateTokenSecurity.js
> +  return Promise.resolve({ jwk: jwksResponse, error: isValid });
En esta funcion vamos a tener que agregar lo que dije en el otro comentario (El de las Promesas en base el resultado). No es correcto que la función solo devuelta sin importar el resultado, una resolve de una promise.

2020-11-08 16:56 UTC, sebalagomarsino requested changes
Agregar tests de integración por favor!

2020-11-08 21:33 UTC, sebalagomarsino requested changes

2020-11-08 21:33 UTC, sebalagomarsino commented on sdk/requests/validateToken.js
> +    // Obtener la jwk del jwks endpoint.
Los comentarios agregados están bien pero pondría una breve descripción sobre que es JWK

2020-11-09 01:00 UTC, facugu1998 commented on sdk/requests/__tests__/index.test.js
> +    validateToken.mockReturnValue(Promise.resolve(result));
![image](https://user-images.githubusercontent.com/8345775/98489668-bd40ec80-220d-11eb-91eb-88c3eec02908.png)

no es eso?

2020-11-09 22:34 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> +    validateToken.mockReturnValue(Promise.resolve(result));
No, ese es el archivo validateToken.test.js, yo digo el index.test.js adentro de la carpeta __tests__ de requests
[index.test.js](https://github.com/elirosselli/pis2020/blob/feature/request-validate-token/sdk/requests/__tests__/index.test.js) (ese es el archivo)

2020-11-10 00:01 UTC, facugu1998 commented on sdk/requests/__tests__/index.test.js
> +    validateToken.mockReturnValue(Promise.resolve(result));
Ahi quedó corregido

2020-11-11 04:52 UTC, belenbrandino commented on sdk/requests/__tests__/index.test.js
> +      error: false,
Esto quedó viejo, agregale el errorCode, errorDescription y message

2020-11-11 04:53 UTC, belenbrandino commented on sdk/requests/__tests__/index.test.js
> +      error: true,
Esto quedó viejo, agregale el errorCode, errorDescription y message

2020-11-11 04:57 UTC, belenbrandino commented on sdk/requests/__tests__/validateToken.test.js
> +      json: () => Promise.reject(Error('fetch rejection')),
no tenes una manera de generar un error de verdad? por ejemplo como sdk/requests/__tests__/refreshToken.test.js linea 98. Si ves la idea es que realmente devolvamos lo que retornaría la api y con eso ver que hace tu programa

2020-11-11 05:00 UTC, belenbrandino commented on sdk/requests/__tests__/validateToken.test.js
> +      status: 200,
lo mismo acá

2020-11-11 05:04 UTC, belenbrandino commented on sdk/security/validateTokenSecurity.js
> +  const { idToken } = getParameters();
que pasa si idToken no existe? Si importa que tenga algo podes devolver un error (x ej. getUserInfo linea 9)

2020-11-11 05:05 UTC, belenbrandino commented on sdk/security/validateTokenSecurity.js
> +    aud: [getParameters().clientId],
lo mismo con el clientId acá (ya hay un error para clientid vacio)

2020-11-11 05:08 UTC, belenbrandino commented on sdk/__tests__/configuration-requests/validateToken-configuration.test.js
> +import { Platform } from 'react-native';
creo que no se usa

2020-11-11 05:08 UTC, belenbrandino commented on sdk/__tests__/configuration-requests/validateToken-configuration.test.js
> +  fetch.mockImplementationOnce(() => Promise.reject(Error('fetch rejection')));
lo mismo de mockear fetch reales

2020-11-11 05:09 UTC, belenbrandino commented on sdk/__tests__/configuration-requests/validateToken-configuration.test.js
> +    Promise.resolve({
aca tambien

2020-11-11 05:10 UTC, belenbrandino commented on sdk/__tests__/configuration-requests/validateToken-configuration.test.js
> +    setParameters({ clientId, idToken });
que pasa si alguno de estos parámetros es vacío?

2020-11-11 05:16 UTC, belenbrandino commented on sdk/interfaces/__tests__/validateToken.test.js
> +      jwks: 'jwks',
esto quedó viejo (agregar los campos en vez de error)

2020-11-11 05:17 UTC, belenbrandino commented on sdk/interfaces/__tests__/validateToken.test.js
> +      error: false,
esto tmb quedo viejo

2020-11-11 05:17 UTC, belenbrandino commented on sdk/interfaces/__tests__/validateToken.test.js
> +      expect(error).toStrictEqual(Error(result));
este error tmb, usa el de failed request

2020-11-11 05:17 UTC, belenbrandino commented on sdk/requests/__tests__/index.test.js
> +      expect(err).toStrictEqual(Error(result));
este tmb ta viejo

2020-11-11 05:19 UTC, belenbrandino commented on sdk/security/__tests__/validateTokenSecurity.test.js
> +      await validateTokenSecurity(jwksResponse);
agergar un tests para parametros clientId e idToken vacios?

2020-11-11 05:20 UTC, belenbrandino commented on sdk/security/validateTokenSecurity.js
> +    aud: [getParameters().clientId],
es más, si que clientId sea vacio te impide hacer todo, deberías chequearlo al prinicpio, como hacemos en las otras funcionalidades (ej login)

2020-11-11 05:21 UTC, belenbrandino commented on sdk/utils/__tests__/encoding.test.js
> +          'InvalidLengthError: Input base64url string is the wrong length to determine padding',
no se si esto es un error nuestro o que, pero si es podriamos adaptarlo a los errores que tenemos

2020-11-11 05:22 UTC, belenbrandino commented on sdk/utils/encoding.js
> +        'InvalidLengthError: Input base64url string is the wrong length to determine padding',
lo mismo de si es un error nuestro o nopi

2020-11-11 05:24 UTC, belenbrandino commented
Revisar si la libreria funciona para ios

2020-11-11 05:39 UTC, belenbrandino commented
Revisar porque no funciona ni en ios ni en android 
<img width="771" alt="Screen Shot 2020-11-11 at 02 34 40" src="https://user-images.githubusercontent.com/37756040/98773167-1d2ec300-23c7-11eb-95b9-83ec13e908d1.png">
<img width="809" alt="Screen Shot 2020-11-11 at 02 38 29" src="https://user-images.githubusercontent.com/37756040/98773171-1ef88680-23c7-11eb-9587-34f1b507e5a6.png">

2020-11-11 20:35 UTC, sebalagomarsino requested changes

2020-11-11 20:35 UTC, slagomarsino-fing commented on sdk/requests/__tests__/validateToken.test.js
> +  it('calls validateToken correctly but fetch rejects', async () => {
Agregar un enter por favor.

2020-11-11 20:35 UTC, sebalagomarsino commented on sdk/security/validateTokenSecurity.js
> +  // Se construye la clave publica para verificar la firma del token.
```suggestion
  // Se construye la clave pública para verificar la firma del token.
```

2020-11-11 20:35 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/validateToken-configuration.test.js
> +}));
Esta bien que mockeemos este modulo?

2020-11-12 02:55 UTC, belenbrandino approved these changes

2020-11-12 07:54 UTC, sebalagomarsino approved these changes

2020-11-12 07:54 UTC, merged