Feature/retries
elirosselli/pis2020 pull request #50
Opened 2020-11-05 02:53 UTC by facugu1998

# Funcion Retries
## Descripción

Se implementa un wrapper de la función fetch que permita ejecutar un número determinado de reintentos.

## Tests

Explique las pruebas unitarias realizadas. Por ejemplo, con una lista:
  - [x] **calls fetch correctly**: la función fetch devuelve correctamente y no se realizan llamadas recursivas.
  - [x] **calls fetch incorrectly**: la función fetch devuelve error, se realizan 5 reintentos y se devuelve el error.
  - [x] **calls fetch correctly after recursion**: la función fetch devuelve error en la primera llamada, luego en el segundo intento devuelve correcto.

2020-11-08 21:46 UTC, sebalagomarsino requested changes
Habría que agregar este fetch para todas las funciones, no? O por qué está solo para el userInfo?

2020-11-08 21:46 UTC, sebalagomarsino commented on sdk/requests/getUserInfo.js
> +// import { fetch } from 'react-native-ssl-pinning';
```suggestion
```

2020-11-08 21:46 UTC, sebalagomarsino commented on sdk/requests/getUserInfo.js
> +import fetchWrapper from '../utils/fetchRetry';
podríamos importarlo como fetch que queda mas lindo

2020-11-08 21:46 UTC, sebalagomarsino commented on sdk/utils/__tests__/fetchRetry.test.js
> +import fetchRetry from '../fetchRetry';
si importamos de fetchRetry como fetch, y para el fetch de ssl pinning podemos escribir `import { fetch as fetchSslPinning } from 'react-native-ssl-pinning';`

2020-11-08 21:46 UTC, sebalagomarsino commented on sdk/utils/__tests__/fetchRetry.test.js
> +  it('calls fetch incorrectly', async () => {
agregar enter

2020-11-08 21:46 UTC, sebalagomarsino commented on sdk/utils/__tests__/fetchRetry.test.js
> +  it('calls fetch correctly after recursion', async () => {
agregar enter

2020-11-08 21:46 UTC, sebalagomarsino commented on sdk/utils/fetchRetry.js
> +export default fetchWrapper;
pondría esta función en un archivo helpers.js (archivo que se va a agregar cuando se mergee lo de AFA) y haria que la función sea un named export, y llamándose fetch solo

2020-11-09 01:31 UTC, facugu1998 commented on sdk/requests/getUserInfo.js
> +// import { fetch } from 'react-native-ssl-pinning';
hay que agregarla a todas si, no quise hacerlo para no modificar todo, pero si ahora se va a llamar fetch, es solo agregar un parametro en los tests

2020-11-12 08:02 UTC, sebalagomarsino requested changes

2020-11-12 08:02 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/getToken-configuration.test.js
> +myModule.fetch = jest.fn();
para que es esto?

2020-11-12 08:02 UTC, sebalagomarsino commented on sdk/requests/__tests__/getUserInfo.test.js
> +    const code = 'jeje';
cambiar a algo mas formal

2020-11-12 08:02 UTC, sebalagomarsino commented on sdk/requests/__tests__/index.test.js
> -import makeRequest from '../index';
Porque se borraron tantas cosas de este archivo?

2020-11-12 17:48 UTC, belenbrandino commented on sdk/__tests__/configuration-requests/getToken-configuration.test.js
> +myModule.fetch = jest.fn();
para mockear solo el fetch y no initializeErrors

2020-11-12 17:53 UTC, belenbrandino commented on sdk/utils/__tests__/fetchRetry.test.js
> +    fetchSslPinning.mockImplementation(() => Promise.resolve('Valid'));
porque los errores tienen esta forma?

2020-11-12 21:25 UTC, sebalagomarsino approved these changes

2020-11-12 21:25 UTC, merged