Feature/return errors
elirosselli/pis2020 pull request #51
Opened 2020-11-09 18:03 UTC by belenbrandino

## Descripción

Se implementaron los errores como se mencionan en la arquitectura, en utils/constants para cada funcionalidad. Se controlaron que ciertos parámetros no sean vacíos (en initialize y en cada funcionalidad) y se implementaron todos los errores encontrados en las pruebas de verificación del sistema. 

## Tests
  - [x] Se cambiaron todas las pruebas unitarias y de integración para adaptarlas a los errores
  - [x] Se agregaron pruebas para los parámetros vacíos controlados en cada función, unitarias y de integración
  - [x] Se agregaron pruebas para los errores controlados en cada función, unitarias y de integración

2020-11-09 21:56 UTC, sebalagomarsino requested changes
Falta testear la línea 18 del módulo `helpers.js` en los tests de integración.

2020-11-09 21:56 UTC, slagomarsino-fing commented on app/App.js
> +                    // }}
Sacar estos comentarios por favor

2020-11-09 21:56 UTC, sebalagomarsino commented on app/LoginButton/index.js
> +      handleCode(respLogin.code);
Podríamos poner loginResponse en vez de respLogin

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/getToken-configuration.test.js
> +  it('calls setParameters and makes a get token request with invalid client id or client id', async () => {
El nombre de este test creo que quedó mal.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/login-configuration.test.js
> +    const resp = await makeRequest(REQUEST_TYPES.LOGIN);
En vez de resp, podemos poner response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/login-configuration.test.js
> +    const resp = await makeRequest(REQUEST_TYPES.LOGIN);
En vez de resp podemos poner response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/login-configuration.test.js
> +      postLogoutRedirectUri: '',
agregaria antes del initialize el getParameters para mostrar que no tenias nada, ejecutas el initialize y después usas getParameters devuelta, así se ve que no había nada y que no guardo nada tampoco.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/login-configuration.test.js
> +      postLogoutRedirectUri: '',
Mismo comentario que lo anterior. Agregaria antes del initialize el getParameters para mostrar que no tenias nada, ejecutas el initialize y después usas getParameters devuelta, así se ve que no había nada y que no guardo nada tampoco.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/logout-configuration.test.js
> +    const resp = await makeRequest(REQUEST_TYPES.LOGOUT);
Pondría `response` en vez de `resp`

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/__tests__/configuration-requests/logout-configuration.test.js
> +    const resp = await makeRequest(REQUEST_TYPES.LOGOUT);
Pondría `response` en vez de `resp`

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/configuration/__tests__/index.test.js
> +      // code: 'code',
Borrar comentario innecesario por favor

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/configuration/__tests__/index.test.js
> +      // code: 'code',
Borrar comentario innecesario por favor

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/configuration/__tests__/index.test.js
> +      // code: 'code',
Borrar comentario innecesario por favor

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/configuration/__tests__/index.test.js
> +    };
Agregar un enter con el test anterior. También cambiar los `as` por los nombres de las variables o algo un poco más formal.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/configuration/index.js
> +    parameters[key] = params[key];
Por qué agregaste esto? Esto hace que el objeto que tenemos nosotros con los parámetros se pueda "agrandar" y no es lo que queremos.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    const errorResp = initialize(
Pondría errorResponse o responseError, pero sin abreviar la palabra response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    const errorResp = initialize(
Pondría errorResponse o responseError, pero sin abreviar la palabra response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    const errorResp = initialize(
Pondría errorResponse o responseError, pero sin abreviar la palabra response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    expect(responseParameters.postLogoutRedirectUri).toStrictEqual('');
Truco, podes poner `const { redirectUri, clientId, clientSecret, postLogoutRedirectUri } = getParameters();` y abajo usarlos como redirectUri, etc, si queres.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +  });
Truco, podes poner `const { redirectUri, clientId, clientSecret, postLogoutRedirectUri } = getParameters();` y abajo usarlos como redirectUri, etc, si queres.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +  });
Truco, podes poner `const { redirectUri, clientId, clientSecret, postLogoutRedirectUri } = getParameters();` y abajo usarlos como redirectUri, etc, si queres.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    expect(responseParameters.postLogoutRedirectUri).toStrictEqual('');
Truco, podes poner `const { redirectUri, clientId, clientSecret, postLogoutRedirectUri } = getParameters();` y abajo usarlos como redirectUri, etc, si queres.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    const errorResp = initialize(
Pondría errorResponse o responseError, pero sin abreviar la palabra response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    const errorResp = initializeErrors(
Pondría errorResponse o responseError, pero sin abreviar la palabra response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/index.js
> +    // Si los parametros clientId, redirectUri y postLogoutRedirectUri no son vacíos se hace el set de los parametros
falto y clientSecret

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/interfaces/index.js
> +};
Corregir tildes de comentarios de este documento. Terminar los comentarios con `.` por favor.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +      clientSecret: 'asdasd',
Poner invalidClientId y invalidClientSecret para mantener formalidad. Invalid o incorrect, lo que prefieras

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +      accessToken: 'incorrectAccessToken',
Acá deberia ser accessToken en vez de incorrectAccessToken, para no confundir a la persona que ve el test.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +      accessToken: 'incorrectAccessToken',
Acá deberia ser accessToken en vez de incorrectAccessToken, para no confundir a la persona que ve el test.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +      accessToken: 'incorrectAccessToken',
Acá deberia ser accessToken en vez de incorrectAccessToken, para no confundir a la persona que ve el test.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +      accessToken: 'incorrectAccessToken',
Acá deberia ser accessToken en vez de incorrectAccessToken, para no confundir a la persona que ve el test.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +    });
Acá deberia ser accessToken en vez de incorrectAccessToken?? Me confundí.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +    const resp = await login();
Pondría `response` en vez de `resp`

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/refreshToken.test.js
> +      clientSecret: 'asdasd',
cambiar a clientId y clientSecret para mantener formalidad

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/__tests__/refreshToken.test.js
> +      clientSecret: 'asdasd',
Cambiar a clientSecret para mantener formalidad.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +  if (type === REQUEST_TYPES.GET_REFRESH_TOKEN && !parameters.refreshToken){
```suggestion
  if (type === REQUEST_TYPES.GET_REFRESH_TOKEN && !parameters.refreshToken) {
```
Para arreglar el linter

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    const respError = initializeErrors(
Pondría responseError o errorResponse pero sin abreviar la palabra response

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
>  };
Agregar un `.` al final de cada comentario por favor.

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    eraseCode();
Por qué se borra el code en caso de éxito del getToken?

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/login.js
> +    // Si hay un clientId, redirectUri y postLogoutRedirectUri setteado, se abre el browser
Faltó clientSecret

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/login.js
>  };
Agregar `.` al final de cada comentario por favor

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/requests/logout.js
> +      return Promise.reject(ERRORS.INVALID_URL_LOGOUT); //  TODO: chequear que esto se haga aca y no en el catch
Por que se deja este TODO?

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/utils/constants.js
> +    // Información de depuración personalizada
Agregarle `.` al final de cada comentario

2020-11-09 21:56 UTC, sebalagomarsino commented on sdk/utils/helpers.js
> +export { initializeErrors };
Agregar el disable del default para todo el archivo en lugar de solo esta linea. Corregir tildes de los comentarios y poner `.` por favor

2020-11-09 23:12 UTC, belenbrandino commented
> Falta testear la línea 18 del módulo `helpers.js` en los tests de integración.

No lo había hecho, porque no sabía si el postLogoutRedirectUri volaba o no, pero lo agrego

2020-11-09 23:33 UTC, belenbrandino commented on sdk/__tests__/configuration-requests/login-configuration.test.js
> +      postLogoutRedirectUri: '',
la parte de que no guardó nada ya se hace

2020-11-09 23:41 UTC, belenbrandino commented on sdk/configuration/index.js
> +    parameters[key] = params[key];
Ni idea. Seguró quedó mal de cuando pepe habia puesto que se pudieran poner cosas vacías. Lo pelo

2020-11-10 00:18 UTC, belenbrandino commented on sdk/requests/__tests__/getToken.test.js
> +    });
accessToken esta bien. Quedó mal la descripción del error. La gracia era que fuera un error distinto a los q se controlan, para que salga por el failed request

2020-11-10 00:25 UTC, belenbrandino commented on sdk/requests/getTokenOrRefresh.js
> +    eraseCode();
Una vez que usas el code para obtener un token deja de ser válido. Entonces lo borras de una y ya le tiras el error de que esta vacío

2020-11-10 00:27 UTC, belenbrandino commented on sdk/requests/logout.js
> +      return Promise.reject(ERRORS.INVALID_URL_LOGOUT); //  TODO: chequear que esto se haga aca y no en el catch
Por que no se como chequearlo

2020-11-10 20:02 UTC, sebalagomarsino commented on sdk/configuration/__tests__/index.test.js
> +    };
Agregar enter antes del `it` por favor para que quede separado del test anterior.

2020-11-10 22:08 UTC, sebalagomarsino requested changes

2020-11-10 22:08 UTC, slagomarsino-fing commented on sdk/interfaces/__tests__/index.test.js
> +    // const responseParameters = getParameters();
Borrar comentario por favor!

2020-11-10 22:08 UTC, slagomarsino-fing commented on sdk/interfaces/__tests__/index.test.js
> +  it('returns error with all parameters setted', () => {
No sería algo tipo `does not return error when all parameters are setted`?

2020-11-10 22:08 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
>      eraseCode();
No me deja responderte a tu mensaje, pero vos decis que hay que borrarlo porque no te sirve para nada mas? Porque no podrías hacer dos veces getToken con el mismo authorization code decís?

2020-11-10 22:10 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    eraseCode();
Ahh, vos decis que hay que borrarlo porque no te sirve para nada mas? Tipo que no podrías hacer dos veces getToken con el mismo authorization code decís?

2020-11-10 22:15 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    eraseCode();
Si esto se queda, entonces escribí el comenatirio y le función arriba, tipo en la linea 75, por ahi, y saca los eraseCode de los otros lados, que es código repetido sino

2020-11-10 23:14 UTC, sebalagomarsino approved these changes

2020-11-10 23:15 UTC, merged