Feature/doc errores
elirosselli/pis2020 pull request #74
Opened 2020-11-16 03:48 UTC by pepesouto

# PR Template

## Descripción

Se agrego al readme los errores de cada funcionalidad.

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +Si alguno de estos parámetros obligatorios es vacío devuelve un error correspondiente a cual es el primero vacío.
pondría devuelve un error indicando cual es el primer parámetro vacío

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +*clientId* vacío retorna `ERRORS.INVALID_CLIENT_ID`.
pondría, si el parámetro *clientId* es vacío retorna ...

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +Por otro lado, si el parámetro production no es booleano se retorna el error `ERRORS.INVALID_PRODUCTION`.
pondría: si **el tipo del** parámetro production no es booleano, se retorna

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que alguno de los parámetros *clientId*, *clientSecret* y *redirectUri* no haya sido seteado, por lo tanto sea vacío, se retorna el error correspondiente al primer parámetro vacio: `ERRORS
Unificaría el formato con el de los errores del login (o lista o texto). Si decidís usar texto, los pondría en el mismo orden, es decir si arriba decís *clientId*, *clientSecret* y *redirectUri* abajo pondría 
correspondiente al primer parámetro vacio, siendo estos: `ERRORS.INVALID_CLIENT_ID`, `ERRORS.INVALID_CLIENT_SECRET` y `ERRORS.INVALID_REDIRECT_URI` respectivamente

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que no exista el parámetro *code* en la url se retorna el error `ERRORS.INVALID_AUTHORIZATION_CODE`.
en la url retornada por el OP?

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que el usuario niegue dar acceso de la información solicitada se retorna el error `ERRORS.ACCESS_DENIED`.
lo escribiría un poco más lindo, además de que debería decir usuario **final**. Algo como lo que dice la arqui: _El usuario final no autoriza a la aplicación móvil RP a acceder a sus datos_

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de error en la request se retorna `ERRORS.FAILED_REQUEST`, en este caso se recomienda revisar que los parámetros de la request sean válidos y comprobar la conexión a internet.
request con cursiva no?

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que alguno de los parámetros *clientId*, *clientSecret* y *redirectUri* no haya sido seteado, por lo tanto sea vacío, se retorna el error correspondiente al primer parámetro vacio: `ERRORS
Lo mismo para todos, deberían tener el mismo formato para describir los errores

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que alguno de los parámetros *clientId*, *clientSecret*, *redirectUri* y *code* no haya sido seteado, por lo tanto sea vacío, se retorna el error correspondiente al primer parámetro vacio:
poner ordenados los errores y lo de respectivamente

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que el *code* sea inválido o haya expirado, y no se puede obtener un nuevo token de forma satisfactoria se retorna `ERRORS.INVALID_GRANT`.
y no se pued**A** obtener un token? token con cursiva. También puede ser vacío el code y retornar el mismo error

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que no se pudo obtener un nuevo token de forma correcta se retorna `ERRORS.INVALID_CLIENT`. Se recomienda verificar que el *client_secret* y *client_id* correspondan con los registrados po
Este error se retorna en caso de que pongas un client id o client secret no registrado ante el OP

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de error en la respuesta del endpoint se retorna `ERRORS.FAILED_REQUEST`.
Les pondría a todas las funciones la misma justificación. Failed request es el ultimo error que tiras dsp de verificar todos los q conoces, osea, si te viene un error desconocido (no controlado), sale por acá

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que alguno de los parámetros *clientId*, *clientSecret* y *redirectUri* sea vacío, se retorna el error correspondiente al primer parámetro vacio: `ERRORS.INVALID_CLIENT_ID`, `ERRORS.INVALI
orden

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +Los casos de errores son muy similares a los de `getToken`.
de la funcionalidad getToken?

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +A diferencia del `getToken`, no se chequea que el code sea vacio, pero en cambio se revisa que que el parámetro `refreshToken` no lo sea. Si refreshToken es vacio se retorna `ERRORS.INVALID_GRANT`.
A diferencia de la funcionalidad getToken? Code con cursiva. Pondría solo ", en cambio se revisa". Al final pondría, en tal caso se retorna ... 
Y vacío lleva tilde

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que el refreshToken sea inválido o haya expirado se retorna `ERRORS.INVALID_GRANT`.
estamos seguros que el refreshToken expira?

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que no se pudo obtener un nuevo token de forma correcta se retorna `ERRORS.INVALID_CLIENT`. Se recomienda verificar que el *client_secret* y *client_id* correspondan con los registrados po
lo mismo que en getToken

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de error en la respuesta endpoint se retorna `ERRORS.FAILED_REQUEST`.
unificar

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
en todos los casos deberíamos decir que cuando no hay error retornamos el no error

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que el *accessToken* sea inválido devuelve un error de tipo `ERRORS.INVALID_TOKEN`.
En caso de que el parámetro ... Además, esto pasa cuando es vacío también

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
>  ```
falta cuando id token es vacío y cuando el sub es inválido

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que alguno de los parámetros *clientId*, *clientSecret* y *redirectUri* no haya sido seteado, por lo tanto sea vacío, se retorna el error correspondiente al primer parámetro vacio: `ERRORS
debería mencionar tmb el error de producción

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
>  Al igual que el `code`, el *token* retornado se guarda en el SDK, con lo que de no necesitar almacenar el *token*, también se puede llamar a `getToken` sin guardar la respuesta.
debería mencionar tmb el error de producción

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
>  El *token* otorgado por ID Uruguay tiene un tiempo de expiración fijo, por lo que una vez transcurrido este tiempo, el *token* pasará a ser inválido. Para obtener un nuevo *token* se debe invocar a l
debería mencionar tmb el error de producción

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de error en la respuesta del endpoint se retorna `ERRORS.FAILED_REQUEST`.
unificar

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +Si alguno de los parámetros obligatorios para la request no se encuentra inicializado, se rechaza la promesa y se retorna un error que especifica cuál parámetro faltó.
el primero que faltó

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +En caso de que el *token* no se pueda validar en el modulo de seguridad se retorna el error `ERRORS.FAILED_REQUEST`.
en ese caso devuelve INVALID_ID_TOKEN

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
> +
falta el ultimo error de failed request

2020-11-16 16:36 UTC, belenbrandino commented on sdk/README.md
>  ### Función logout
en los errores de logout habla de parámetros obligatorios: cuales? Y falta unificar lo de failed request

2020-11-16 18:07 UTC, belenbrandino commented
Faltan todos estos errores en contributing.md

2020-11-16 21:04 UTC, belenbrandino requested changes
.

2020-11-16 23:42 UTC, elirosselli requested changes
Holi :) Deberíamos cambiar las llamadas de ejemplo a las funciones para que todas usen try-catch como el login

2020-11-18 23:41 UTC, pepesouto commented on sdk/README.md
> +En caso de que el *code* sea inválido o haya expirado, y no se puede obtener un nuevo token de forma satisfactoria se retorna `ERRORS.INVALID_GRANT`.
si es vacio el code no retorna `ERRORS.INVALID_AUTHORIZATION_CODE` ?

2020-11-22 00:58 UTC, belenbrandino commented
> Faltan todos estos errores en contributing.md. Hablar con Leo sobre si esta bien que los errores estén definidos abajo del todo en sdk/readme y vos los menciones antes

Todavía no lei las cosas nuevas, si siguen la semana que viene las leo :)

2020-11-22 13:31 UTC, elirosselli approved these changes

2020-11-22 13:36 UTC, belenbrandino approved these changes

2020-11-22 13:38 UTC, merged