bugfix/integration tests coverage
elirosselli/pis2020 pull request #80
Opened 2020-11-16 23:39 UTC by manueleirea

# Take integration tests coverage to 100%

## Descripción

Se realizaron cambios en los tests, como se indica en **Tests**. Además, se quitó la posibilidad de tener un *state* vacío en la implementación de logout, ya que este parámetro es ahora provisto por el SDK.

## Tests

  - [x] Se modificaron algunos tests de integración de getUserInfo para que se correspondieran correctamente con sus descripciones.
  - [x] Se modificaron algunos tests de integración de makeRequest del tipo getUserInfo para que se correspondieran correctamente con sus descripciones.
  - [x] Se agregaron tests de integración de getUserInfo para alcanzar un 100% de coverage.
  - [x] Se agregaron tests de integración de makeRequest del tipo getUserInfo para alcanzar un 100% de coverage.
  - [x] Se quitó un test unitario de logout que debido al cambio detallado en **Descripción**, no tenía sentido de ser.
  - [x] Se cambió el nombre de dos constantes en los tests de integración de logout y de makeRequest del tipo logout, para que se este se adecuara más a su significado.

2020-11-16 23:41 UTC, sebalagomarsino requested changes

2020-11-16 23:41 UTC, sebalagomarsino commented on sdk/requests/logout.js
> +          state: state[1],
Esto se puede romper, en el caso de que  te manden una url sin state, con un posible hackeo por ejemplo.

2020-11-17 04:21 UTC, manueleirea commented on sdk/requests/logout.js
> +          state: state[1],
Si te mandan una url sin state, no va a entrar porque el if de urlCheck === logoutEndpoint() va a dar false.

2020-11-17 11:46 UTC, sebalagomarsino commented on sdk/requests/logout.js
> +          state: state[1],
Ah, okey, quizás que hay que hacer una rama bugfix para cambiar como se hace esto, así el usuario sabe que es porque le llego el state mal, pero esta bien tu cambio entonces

2020-11-17 21:15 UTC, sebalagomarsino approved these changes

2020-11-17 21:15 UTC, merged