Hacer throw de los errores en todas las funciones
elirosselli/pis2020 pull request #81
Opened 2020-11-17 00:07 UTC by belenbrandino

## Descripción

Todas las funciones que retornaban errores ahora hacen throw de los mismos (menos para el error NO_ERROR).

## Tests
Se cambiaron todas las pruebas unitarias y de integración para adaptarlas a estos cambios.

2020-11-17 00:15 UTC, sebalagomarsino requested changes

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/configuration/__tests__/index.test.js
> +
agregar un expect.assertions() al final de este test

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    }
Agregar expect.assertions al final de este test

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    }
Agregar expect.assertions al final de este test

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    }
Agregar expect.assertions al final de este test

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/interfaces/__tests__/index.test.js
> +    }
Agregar expect.assertions al final de este test

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    }
me resulta raro esto, que simplemente hagas try catch para poder borrar el code, quizás initializeErrors, al ser una función interna, no tenga que tener ese comportamiento de devolver una excepcion

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/requests/login.js
> +        ERRORS.INVALID_CLIENT_ID.errorCode)
Esto no hace lo que queres que haga, siempre va a dar true, porque ERRORS.INVALID_CLIENT_SECRET.errorCode o ERRORS.INVALID_CLIENT_ID.errorCode son true, tenes que igualarlo con cada uno.

2020-11-17 00:15 UTC, sebalagomarsino commented on sdk/requests/login.js
> +        ERRORS.INVALID_CLIENT_ID.errorCode)
Al hacer esto no cambia poner el error.errorCode && anterior, ya que sino llega a haver error code, este va a ser undefined y la comparación te va a dar false.

2020-11-17 00:22 UTC, belenbrandino commented on sdk/requests/getTokenOrRefresh.js
> +    }
que hago?

2020-11-17 00:24 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    }
si initializeErrors no devuelve un throw se puede hacer igual, no?

2020-11-17 00:39 UTC, belenbrandino commented on sdk/requests/getTokenOrRefresh.js
> +    }
si, exactamente como estaba antes

2020-11-17 11:43 UTC, sebalagomarsino requested changes

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +    }
entonces quizás dejarlo como estaba antes y hacer el throw en initialize, podríamos?

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +    );
No es necesario que el error sea tan fancy, no nos importa el error que devuelve LinkingOpenUrl y ademas nunca va a ser de esa forma. Podríamos poner ` mockLinkingOpenUrl.mockImplementation(() => Promise.reject());`

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/__tests__/interfaces-integration/login.test.js
> +    );
No es necesario que el error sea tan fancy, no nos importa el error que devuelve LinkingOpenUrl y ademas nunca va a ser de esa forma. Podríamos poner ` mockLinkingOpenUrl.mockImplementation(() => Promise.reject());`

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/__tests__/interfaces-integration/login.test.js
> +  });
Poner expect.assertions

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/__tests__/interfaces-integration/initialize.test.js
> +    }
Poner expect assertions al final de este test

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/__tests__/requests-integration/login.test.js
> +  });
Pone expect.assertions

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/__tests__/requests-integration/login.test.js
> +    );
No es necesario que el error sea tan fancy, no nos importa el error que devuelve LinkingOpenUrl y ademas nunca va a ser de esa forma. Podríamos poner ` mockLinkingOpenUrl.mockImplementation(() => Promise.reject());`

2020-11-17 11:43 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +  });
Agregar expect.assertions

2020-11-17 16:39 UTC, belenbrandino commented on sdk/requests/__tests__/login.test.js
> +    );
Es para cubrir una linea de coverage. En el caso de que el error sea un error pero no sea del tipo de los nuestros (tenga errorCode distinto). Hacer lo que vos decis no me sirve

2020-11-17 16:40 UTC, belenbrandino commented on sdk/requests/getTokenOrRefresh.js
> +    }
como poder se puede. Pero hablenlo bien porque no quiero hacer cosas al pedo

2020-11-17 16:40 UTC, belenbrandino commented on sdk/__tests__/interfaces-integration/login.test.js
> +    );
lo mismo que en el anterior

2020-11-17 16:40 UTC, belenbrandino commented on sdk/__tests__/requests-integration/login.test.js
> +    );
same

2020-11-17 20:54 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +    );
que linea? y corriendo que comando?

2020-11-17 21:12 UTC, belenbrandino commented on sdk/requests/__tests__/login.test.js
> +    );
en la linea de login donde se hace if (
       error &&
       (error.errorCode === ERRORS.INVALID_REDIRECT_URI.errorCode ||
         error.errorCode === ERRORS.INVALID_CLIENT_SECRET.errorCode ||
         error.errorCode === ERRORS.INVALID_CLIENT_ID.errorCode)
     )

2020-11-17 21:13 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +    );
probe poniendo `mockLinkingOpenUrl.mockImplementation(() => Promise.reject());` y la linea quedaba cubierta

2020-11-17 21:14 UTC, belenbrandino commented on sdk/requests/__tests__/login.test.js
> +    );
tas seguro que no es porque está en otros tests tmb?

2020-11-17 21:19 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +    );
<img width="759" alt="Captura de Pantalla 2020-11-17 a la(s) 18 18 29" src="https://user-images.githubusercontent.com/48483705/99451747-6ddf7800-2901-11eb-9840-f9b071891e1f.png">

2020-11-17 21:20 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +    );
Cambiandole la linea que te decia

2020-11-17 21:22 UTC, belenbrandino commented on sdk/requests/__tests__/login.test.js
> +    );
oki yo había probado eso, pero ta se ve que me equivoqué en otra cosa. Despues lo cambio

2020-11-17 23:30 UTC, elirosselli commented on sdk/requests/getTokenOrRefresh.js
> +    }
Meto cuchara que creo que de cualquiera de las dos formas es correcto, así que lo dejaría con lo que te lleve menos tiempo

2020-11-18 22:09 UTC, sebalagomarsino approved these changes

2020-11-18 22:09 UTC, merged