Feature/documentacion validate token contributing
elirosselli/pis2020 pull request #82
Opened 2020-11-17 01:44 UTC by facugu1998

# Documentacion validate token en contributing
## Descripción

Se agrega en el archivo CONTRIBUTING.md la documentación de validateToken.

## Tests

No aplica

2020-11-17 17:21 UTC, belenbrandino requested changes

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +La funcionalidad de validateToken se encarga de validar el id_token provisto por IDUruguay. Para poder realizar dicha acción se obtiene el `jwks` (**JSON Web Key Set**), que es un conjuto de `jwk` ([
validateToken en negrita? :) e id_token con cursiva 
despues dice "que es un conjuto de .." conjunto le falta una n

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +La funcionalidad de validateToken se encarga de validar el id_token provisto por IDUruguay. Para poder realizar dicha acción se obtiene el `jwks` (**JSON Web Key Set**), que es un conjuto de `jwk` ([
Creo que no queda muy claro a que te referis con "validar"

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +Una vez obtenido el `jwks` correspondiente, se procede a validar el `idToken` obtenido en una llamada a `getToken` o `refreshToken`, para lo cual se invoca a la función `validateTokenSecurity` del co
creo que en todas las doc cuando se refiere a una función se pone en negrita o cursiva, haría lo mismo acá
Y creo que más arriba cuando se describen los componentes de seguridad, les llama módulos en vez de componente

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +En caso de que el `id_token` sea inválido, se retorna el error `ERRORS.INVALID_ID_TOKEN`.
o vacío. Tmb cuando el client Id es vacío se retorna error :) Igual eso podría ir solo en el código o solo en la parte de parámetros

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +- **sdk/requests/validateToken.js**: Donde se implementa la función `validateToken`. Esta función se encarga de realizar la *JWKS Request* al *JWKS Endpoint*, obteniendo el *JWKS*, además de llamar a
módulo lleva tilde

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +- **sdk/interfaces/index.js**: Donde se invoca la función de **makeRequest**.
le agregaría con el tipo de request validate token

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +- **sdk/utils/constants.js**: Contiene las constantes a utilizar.
constantes no se usa más, ahora usa errors.js

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +Dentro del archivo `requests/validateToken.js`, se chequea que los parámetros requeridos (*clientId* e *idToken*) existan.
agregaría que si son vacíos se rechaza la promesa retornando un error correspondiente

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +En el cuerpo de la función de **validateToken** se encuentra un bloque de try y uno de catch. Con esto se logra que si la función se ejecuta de forma incorrecta se rechaza la función devolviendo un c
Capaz q lo reescribiría un poco de manera que se entienda que el fetch está dentro del try
Dsp donde dice "devolviendo un codigo de error" código lleva tilde. Además lo que se rechaza es la promesa.
Aclararía que te devuelve el validateTokenSecurity, y que la llamas con el resultado del fetch

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +Posteriormente se agrega una capa extra de validación, con otros atributos. Para esto primero se decodifica el *id_token* ([JWT](https://tools.ietf.org/html/rfc7519)), obteniendo el *header* y el *pa
"Del *header* se valida el atributo *kid*, comparándola" sería comparándolo no? porque estamos hablando del atributo

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +|-----------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------
Capaz que pondría tipo en la siguiente tabla se puede ver ...

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +Por último se comprueba que las validaciones anteriores hayan sido con éxito, y en ese caso se resuelve la función con lo siguiente:
se hayan realizado con éxito? capaz queda más lindo
y en tal caso se resuelve la **promesa**, retornando los siguientes valores

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +```
faltaría hablar de que validateToken retorna failed request cuando algo falla

2020-11-17 17:21 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +
faltó que parámetros recibe y que retorna

2020-11-18 02:20 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +- **sdk/utils/constants.js**: Contiene las constantes a utilizar.
faltó borrar constants (fijate por las dudas pero yo habia visto que no se usaba)

2020-11-18 02:23 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +
esto todavia falta

2020-11-18 02:23 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +
sigue faltando

2020-11-18 02:30 UTC, belenbrandino commented on sdk/CONTRIBUTING.md
> +```
falta estooo

2020-11-20 22:15 UTC, belenbrandino approved these changes

2020-11-20 22:19 UTC, sebalagomarsino approved these changes

2020-11-20 22:20 UTC, merged