Documentación módulo configuración
elirosselli/pis2020 pull request #83
Opened 2020-11-17 05:21 UTC by belenbrandino

## Descripción

Documentación de las funcionalidades del módulo de configuración (getParameters, setParameters, clearParameters, resetParameters, eraseCode, eraseState).

## Tests
No aplica.

2020-11-17 23:25 UTC, elirosselli requested changes
Holi :) dejé unos comentarios. Me queda la duda de si en el README tenemos que actualizar algo con respecto a estas funciones?

2020-11-17 23:25 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +Las funcionalidades de este módulo se encargarán de establecer, modificar o borrar los parámetros que se utilizan durante la ejecución del componente. Estos parámetros se encuentran en el objeto **pa
Diría 'pares' en vez de 'parejas'

2020-11-17 23:25 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +En caso de que el valor correspondiente a la clave actual sea distinto de vacío, es decir que no se permiten setear valores vacíos, se ejecuta un bloque [*try-catch*](https://developer.mozilla.org/es
el "es decir que no se permiten setear valores vacíos" lo pondría como una oración a parte porque creo que no queda muy claro ahora. Setean debería ir en cursiva?

2020-11-17 23:25 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +En caso de error, se lanza una excepción indicando el *error* retornado por la función de validación de parámetros, con la sentencia [*throw*](https://developer.mozilla.org/es/docs/Web/JavaScript/Ref
Setean iría en curisva?

2020-11-17 23:25 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +El funcionamiento general de **resetParameters** consiste en recorrer los valores de los parámetros y borrarlos (setearlos al *string* vacío), a excepción del parámetro mencionado anteriormente.
setearlos en cursiva?

2020-11-17 23:25 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +Esta función utiliza *Object.keys()* que retorna un arreglo de las propiedades *clave* de un objeto, en este caso, el nombre de los parámetros guardados en *parameters*, y con la función *forEach(fun
y acá

2020-11-18 21:26 UTC, elirosselli requested changes
Holi dejé unos comentarios

2020-11-18 21:26 UTC, elirosselli commented on sdk/README.md
> +```
Podemos poner directamente asi
```javascript
const { redirectUri } = getParameters();
```

2020-11-18 21:26 UTC, elirosselli commented on sdk/CONTRIBUTING.md
> +En caso de error, se lanza una excepción indicando el *error* retornado por la función de validación de parámetros, con la sentencia [*throw*](https://developer.mozilla.org/es/docs/Web/JavaScript/Ref
Sigue sin estar en cursiva creo :see_no_evil:

2020-11-18 21:26 UTC, elirosselli commented on sdk/README.md
> +Observar que esta función no permite setear parámetros vacíos.
Setear en cursiva

2020-11-18 21:26 UTC, elirosselli commented on sdk/README.md
>  Se debe inicializar el SDK con la función `initialize`, que recibe como parámetros: *redirect_uri*, *client_id*, *client_secret*, *production* y *scope*. Estos últimos parámetros son opcionales. El p
En vez de "Estos ultimos" diría "Estos dos últimos"

2020-11-18 21:26 UTC, elirosselli commented on sdk/README.md
> +Esta función *setea* los parámetros en el SDK. Observar que algunos de los parámetros pueden ser *seteados* también utilizando la función *initialize*. Para poder setear los parámetros, alcanza con p
setear en cursiva dos veces

2020-11-20 22:20 UTC, belenbrandino commented on sdk/README.md
> +```
si, lo puse a propósito asi. Pero como quierassss

2020-11-20 22:23 UTC, erosselli approved these changes

2020-11-20 22:25 UTC, elirosselli approved these changes

2020-11-20 22:26 UTC, merged