Feature/calling functions mutiple times 2
elirosselli/pis2020 pull request #93
Opened 2020-11-20 03:42 UTC by facugu1998

# Calling functions multiple times

## Descripción

Se agregan mutexes en las requests de forma que no se puedan realizar dos requests simultaneamente.

## Tests

Se modifican los tests unitarios de requests para mockear la clase Mutex.

2020-11-20 22:38 UTC, sebalagomarsino requested changes

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/__tests__/getToken.test.js
> +const mockFunc = jest.fn();
Cambiar nombre por `mockMutex`.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/__tests__/getUserInfo.test.js
> +const mockFunc = jest.fn();
Cambiar nombre por mockMutex.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/__tests__/login.test.js
> +const mockFunc = jest.fn();
Cambiar nombre por mockMutex.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/__tests__/logout.test.js
> +const mockFunc = jest.fn();
Cambiar nombre por mockMutex.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/__tests__/refreshToken.test.js
> +const mockFunc = jest.fn();
Cambiar nombre por mockMutex.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/__tests__/validateToken.test.js
> +const mockFunc = jest.fn();
Cambiar nombre por mockMutex.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/getTokenOrRefresh.js
> +  const release = await MUTEX.getTokenOrRefreshMutex.acquire();
Cambiar nombre por mutexRelease.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/getUserInfo.js
> +  const release = await MUTEX.getUserInfoMutex.acquire();
Cambiar nombre por mutexRelease.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/login.js
> +  const release = await MUTEX.loginMutex.acquire();
Cambiar nombre por mutexRelease.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/logout.js
> +  const release = await MUTEX.logoutMutex.acquire();
Cambiar nombre por mutexRelease.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/validateToken.js
> +  const release = await MUTEX.validateTokenMutex.acquire();
Cambiar nombre por mutexRelease.

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/requests/validateToken.js
> +    console.log(idToken);
Quitar console.log

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/utils/constants.js
> +// Se crean los mutex.
No es necesario este comentario

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/utils/constants.js
> +// Se exponen los mutex de manera global.
No es necesario este comentario

2020-11-20 22:38 UTC, sebalagomarsino commented on sdk/utils/constants.js
> +export { REQUEST_TYPES, PARAMETERS, ACR_LIST, AMR_LIST, MUTEX };
Agregar enter

2020-11-21 19:27 UTC, ssantiacevedo approved these changes

2020-11-21 21:05 UTC, sebalagomarsino approved these changes

2020-11-21 21:07 UTC, merged